### ISSUE TITLE
sudoswap

### ISSUE THREAD

**Issue by sudo-owen** [0xmons/TODO#103]
- https://pieroxy.net/blog/pages/lz-string/index.html for encoding urls

**Comment by sudo-owen** [comment]
- fix fonts on mobile

**Comment by nextroy** [comment]
Product Wishlist 
---
1. Instead of filling in contract details, provide a standard search and browsing patterns to select your NFT and/or any ERC20 asset. Can be compatible. 
2. Show most recent trades / highest trades / cumulative trade volume (in $) in some form of top level analytics.
3. Show a list of public trades available (anyone would go and act on them)
4. Let a user decide if they want to keep a trade private (only a whitelisted address can go and execute it? )

**Comment by sudo-owen** [comment]
from cybersage:

UI Feedback
1. I think the select asset type (721/20/1155) could be on the same page as the swap. even better would be not requiring user to select which asset type, the app can auto detect based on asset selected.
2. assets could be pulled from connected wallet in addition to contract ID. Could include a visual + asset name options in a dropdown menu for user friendliness.
![updated-ui](https://media.discordapp.net/attachments/820327623288815697/838448879862415390/unknown.png?width=1402&height=897)

**Comment by sudo-owen** [comment]
https://stackoverflow.com/questions/40314732/angular-2-2-way-binding-with-ngmodel-in-ngfor

**Comment by sudo-owen** [comment]
refactor to auto-check name on input:
https://stackoverflow.com/questions/53654938/how-to-identify-which-item-in-formarray-emitted-valuechanges-event

**Comment by sudo-owen** [comment]
- make sure the For address works
- make sure expiry date works
- display on the front-end
- grab images and display on the trade side

**Comment by sudo-owen** [comment]
- ERC721s are failing with a NaN for some reason

**Comment by sudo-owen** [comment]
* nftx/muse liq pool integration for certain contracts
* opensea api integration

**Comment by sudo-owen** [comment]
https://twitter.com/0xCudl/status/1399823790113234944

^ add better mooncats

**Comment by sudo-owen** [comment]
add multicall to parse the info using less requests

**Comment by sudo-owen** [comment]
https://github.com/vasa-develop/nft-tokenlist

**Comment by sudo-owen** [comment]
look into using `ethers.getAddress` to allow for all address types
